---
- name: working with apache
  hosts: all
  tasks:
    - name: Get the publicip
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        return_content: yes
      register: myoutput

    - set_fact: myip="{{myoutput.content}}"

    - name: Installing apache
      yum:
        name: httpd
        state: latest
    - name: copy index.html
      template:
        src: index.html
        dest: /var/www/html/index.html

    - name: Enable httpd
      systemd:
        name: httpd
        enabled: yes

    - name: Restart httpd
      systemd:
        name: httpd
        state: restarted

    - name: Update httpd.conf file
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#ServerName www.example.com'
        replace: 'ServerName {{myip}}'
      notify: restart apache

  handlers:
    - name: restart apache
      systemd:
        name: httpd
        state: restarted
